### ISSUE TITLE
username_pw set example.

### ISSUE THREAD

**Issue by castaway2000** [groove-x/mqtt_bridge#75]
Could i get an example of username and password set for paho as it relates to the demo config?

**Comment by stijnb1234** [comment]
+1

**Comment by stijnb1234** [comment]
Found it:

```yml
account:
  username: ""
  password: ""
```
